package:
  name: highfive
  version: 2.2

source:
  git_url: https://github.com/BlueBrain/HighFive
  git_tag: v2.2

build:
  number: 3

requirements:
  build:
    - cmake
    - {{compiler("cxx")}}

  host:
    - hdf5 {{ hdf5 }}
    
  run:
    - hdf5 {{ hdf5 }}

about:
  home: https://bluebrain.github.io/HighFive/
  license: BSL-1.0
  summary: 'HighFive - Header-only C++ HDF5 interface'
